export const testDatabase = [
  {
    product_id: 1,
    name: "Perfume A",
    price: "99.99",
    stock_quantity: 999,
    image_url: "t",
    image: "/perfume-a.jpg",
    shopName: "Luxury Scents",
    shopImage: "/shop1.jpg",
    gender_target: "Female",
    fragrance_strength: "Eau de Parfum (EDP)",
  },
  {
    product_id: 2,
    name: "Perfume B",
    price: "149.99",
    stock_quantity: 999,
    image_url: "t",
    image: "/perfume-b.jpg",
    shopName: "Aroma Bliss",
    shopImage: "/shop2.jpg",
    gender_target: "Male",
    fragrance_strength: "Extrait de Parfum",
  },
  {
    product_id: 3,
    name: "Perfume C",
    price: "199.99",
    stock_quantity: 999,
    image_url: "t",
    image: "/perfume-c.jpg",
    shopName: "Elite Fragrance",
    shopImage: "/shop3.jpg",
    gender_target: "Unisex",
    fragrance_strength: "Eau de Toilette (EDT)",
  },
  {
    product_id: 4,
    name: "Perfume D",
    price: "129.99",
    stock_quantity: 999,
    image_url: "t",
    image: "/perfume-d.jpg",
    shopName: "Scented Dreams",
    shopImage: "/shop4.jpg",
    gender_target: "Female",
    fragrance_strength: "Eau Fraiche/mists",
  },
  {
    product_id: 5,
    name: "Perfume E",
    price: "179.99",
    stock_quantity: 999,
    image_url: "t",
    image: "/perfume-e.jpg",
    shopName: "Pure Essence",
    shopImage: "/shop5.jpg",
    gender_target: "Male",
    fragrance_strength: "Eau de Cologne (EDC)",
  },
];
