export const testDatabase = [
  {
    productId: 1,
    name: "Perfume A",
    price: 99.99,
    image: "/perfume-a.jpg",
    shopName: "Luxury Scents",
    shopImage: "/shop1.jpg",
    gender: ["Female"],
    ageRange: ["18-24"],
    fragranceTone: ["Floral", "Fruity"],
    fragranceStrength: ["Eau de Parfum (EDP)"],
  },
  {
    productId: 2,
    name: "Perfume B",
    price: 149.99,
    image: "/perfume-b.jpg",
    shopName: "Aroma Bliss",
    shopImage: "/shop2.jpg",
    gender: ["Male"],
    ageRange: ["25-34"],
    fragranceTone: ["Spicy", "Woody"],
    fragranceStrength: ["Extrait de Parfum"],
  },
  {
    productId: 3,
    name: "Perfume C",
    price: 199.99,
    image: "/perfume-c.jpg",
    shopName: "Elite Fragrance",
    shopImage: "/shop3.jpg",
    gender: ["Unisex"],
    ageRange: ["18-24", "25-34"],
    fragranceTone: ["Citrus", "Fresh"],
    fragranceStrength: ["Eau de Toilette (EDT)"],
  },
  {
    productId: 4,
    name: "Perfume D",
    price: 129.99,
    image: "/perfume-d.jpg",
    shopName: "Scented Dreams",
    shopImage: "/shop4.jpg",
    gender: ["Female", "Unisex"],
    ageRange: ["Under 18", "18-24"],
    fragranceTone: ["Fruity", "Gourmand"],
    fragranceStrength: ["Eau Fraiche/mists"],
  },
  {
    productId: 5,
    name: "Perfume E",
    price: 179.99,
    image: "/perfume-e.jpg",
    shopName: "Pure Essence",
    shopImage: "/shop5.jpg",
    gender: ["Male"],
    ageRange: ["25-34", "35-44"],
    fragranceTone: ["Woody", "Leather"],
    fragranceStrength: ["Eau de Cologne (EDC)"],
  },
];
